# Generated by Django 4.2.4 on 2024-10-08 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interface_etl_estatistica', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CsvData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='csv_files/')),
            ],
        ),
    ]
